# Generated by Django 3.2.14 on 2022-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_path', models.TextField()),
                ('crontab', models.CharField(default='0 * * * *', max_length=20)),
                ('dest_dir_path', models.TextField()),
            ],
        ),
    ]
